CC = gcc
CFLAGS = $(shell pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0)
LDFLAGS = $(shell pkg-config --libs gstreamer-1.0 gstreamer-video-1.0)
SRC_DIR = basic
SRC = $(SRC_DIR)/basic_video_test.c
OUT_DIR = build
OUT = $(OUT_DIR)/basic_video_test

all: $(OUT)

$(OUT): $(SRC)
	@echo "Compiling $< to $@"
	@mkdir -p $(OUT_DIR)
	@$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

clean:
	@rm -rf $(OUT_DIR)